[tool.ruff]

select = ["E", "F", "Q", "B"]
fixable = ["A", "B", "C", "D", "E", "F", "Q"]

exclude = [
    ".git",
    ".github",
    ".vscode",
    "datafiles",
    "__pycache__"
]

line-length = 120
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.per-file-ignores]
"*/*__init__.py" = ["F401"]