"""Our various autogenerated bet datatypes."""

import dataclasses

from mongo.datatypes.basedatatypes import BaseDBObject


@dataclasses.dataclass(frozen=True)
class AutoGeneratedBetDB(BaseDBObject):
    """A dataclass to represent an autogenerated bet."""

    type: str
    """The type the autogenerated bet belongs to."""
    title: str
    """The title of the bet."""
    options: list[str]
    """The list of options for the bet."""
    channel_members: list[int] = dataclasses.field(default_factory=list)
    """The list of required user IDs for this bet to be selected. Could be empty."""
    voice_channel: bool | int = False
    """Whether we should fill options from the list of user IDs in the voice channel."""
    fill: bool = False
    """Whether to fill the options with 'other'."""
    archived: bool = False
    """Whether a bet is archived or not."""
