name: Build and push Docker Image [main]

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: elliotsloman
          password: ${{ secrets.dockerhub_token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e
        with:
          images: elliotsloman/bsebot
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIPHY_TOKEN=${{ secrets.GIPHY_TOKEN }}
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            GIT_USER=ESloman
            GIT_PASS=${{ secrets.GIT_PASS }}
            GITHUB_API_KEY=${{ secrets.GIT_API_KEY }}
