---
name: Release

on:
  push:
    branches:
      main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  pushing:
    if: startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: esloman
          password: ${{ secrets.dockerhub_token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: esloman/bsebot
          tags: |
            type=sha
            type=semver,pattern={{version}},enable=${{ startsWith(github.event.head_commit.message, 'release') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') && startsWith(github.event.head_commit.message, 'release')}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  