name: Pytest

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Pytest and coverage
    environment: ${{ github.ref == 'refs/heads/main' && 'build' || 'test' }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage pytest-cov
      - name: Pytest + Coverage
        run: |
          coverage run --source . -m pytest
          coverage report --omit=tests/*
          coverage html --omit=tests/*
          coverage xml --omit=tests/*
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
