
from discord import Interaction, SelectOption
from discord.ui import Select

from mongo.bsedataclasses import AutoGeneratedBets


class AutogenerateConfigSelect(Select):
    def __init__(self):
        self.autogenerated = AutoGeneratedBets()

        options = [
            SelectOption(label=option[0], value=option[1]) for option in
            [
                ("Add new category", "category"),
                ("Add a new bet", "new")
            ]
        ]

        super().__init__(
            disabled=False,
            placeholder="Select what you want to do...",
            min_values=1,
            max_values=1,
            options=options
        )

    async def callback(self, interaction: Interaction):
        """

        :param interaction:
        :return:
        """
        selected_amount = interaction.data["values"][0]
        for option in self.options:
            option.default = option.value == selected_amount

        await self.view.update(interaction)


class AutogenerateCategorySelect(Select):
    def __init__(self):
        self.autogenerated = AutoGeneratedBets()
        categories = self.autogenerated.get_bet_categories()

        options = [
            SelectOption(label=category.title(), value=category) for category in categories if category != "pook"
        ]

        super().__init__(
            disabled=False,
            placeholder="Select category to create new auto bet for",
            min_values=1,
            max_values=1,
            options=options
        )

    async def callback(self, interaction: Interaction):
        """

        :param interaction:
        :return:
        """
        selected_amount = interaction.data["values"][0]
        for option in self.options:
            option.default = option.value == selected_amount

        await self.view.update(interaction)
