"""Autogenerate selects."""

from discord import Interaction, SelectOption

from discordbot.selects.bseselect import BSESelect
from mongo.bsedataclasses import AutoGeneratedBets


class AutogenerateConfigSelect(BSESelect):
    """Class for autogenerate config select."""

    def __init__(self) -> None:
        """Initialisation."""
        self.autogenerated = AutoGeneratedBets()

        options = [
            SelectOption(label=option[0], value=option[1])
            for option in [("Add new category", "category"), ("Add a new bet", "new")]
        ]

        super().__init__(
            disabled=False,
            placeholder="Select what you want to do...",
            min_values=1,
            max_values=1,
            options=options,
        )

    async def callback(self, interaction: Interaction) -> None:
        """Callback method.

        Args:
            interaction (Interaction): the interaction to callback to
        """
        selected_amount = interaction.data["values"][0]
        for option in self.options:
            option.default = option.value == selected_amount

        await self.view.update(interaction)


class AutogenerateCategorySelect(BSESelect):
    """Class for autogenerate config select."""

    def __init__(self) -> None:
        """Initialisation."""
        self.autogenerated = AutoGeneratedBets()
        categories = self.autogenerated.get_bet_categories()

        options = [
            SelectOption(label=category.title(), value=category) for category in categories if category != "pook"
        ]

        super().__init__(
            disabled=False,
            placeholder="Select category to create new auto bet for",
            min_values=1,
            max_values=1,
            options=options,
        )

    async def callback(self, interaction: Interaction) -> None:
        """Callback method.

        Args:
            interaction (Interaction): the interaction to callback to
        """
        selected_amount = interaction.data["values"][0]
        for option in self.options:
            option.default = option.value == selected_amount

        await self.view.update(interaction)
