
from discord import Interaction, SelectOption
from discord.ui import Select


class ConfigSelect(Select):
    _values = [
        ("Admins", "admins"),
        ("Autogenerated bets", "autogenerate"),
        ("BSEddies", "bseddies"),
        ("Daily Salary", "salary"),
        ("Daily Salary Message", "daily_salary"),
        ("Revolution Event", "revolution"),
        ("Spoiler Threads", "threads"),
        ("Valorant", "valorant"),
        ("Wordle Config", "wordle"),
        ("Wordle Emoji Reaction Config", "wordle_reactions")
    ]

    def __init__(self, configurable_items: list = None):

        if not configurable_items:
            configurable_items = self._values

        options = [
            SelectOption(label=opt[0], value=opt[1]) for opt in configurable_items
        ]

        super().__init__(
            disabled=False,
            placeholder="Select item to configure...",
            min_values=1,
            max_values=1,
            options=options
        )

    async def callback(self, interaction: Interaction):
        """

        :param interaction:
        :return:
        """
        selected_amount = interaction.data["values"][0]
        for option in self.options:
            option.default = option.value == selected_amount

        await interaction.response.edit_message(view=self.view)
